import Link from 'next/link'
import { courseSessions } from '@/lib/course/content'
import { IllustrationFigure } from '@/components/illustrations/illustration-figure'
export function CourseOverview({teacher=false}:{teacher?:boolean}){return <div className="course-page mx-auto max-w-4xl">
 <header><p className="studio-eyebrow">Read · Notice · Write · Revise</p><h1 className="studio-heading mt-4">The Short Story Workshop</h1><p className="mt-5 font-serif text-2xl leading-9">From noticing to revision, one deliberate choice at a time.</p><p className="mt-5 max-w-2xl leading-8 text-studio-muted">A flexible journey alongside your writing group. Begin with the first session or bring a piece you already care about. Your teacher will guide the pace; these are sessions, not deadlines.</p></header>
 <section className="my-9 grid items-center gap-8 border-y border-studio-line py-8 sm:grid-cols-2"><div><p className="studio-eyebrow">Start here</p><h2 className="literary-title mt-3 text-3xl">Begin again.</h2><p className="mt-4 leading-7">You need neither a finished idea nor a polished page. Find one detail worth following.</p><Link href="/app/course/begin-again" className="studio-primary mt-5">Open the first session</Link></div><IllustrationFigure attrs={{illustrationId:'openings'}} /></section>
 <div className="grid gap-9 sm:grid-cols-2"><section><h2 className="literary-title text-2xl">A rhythm you can return to</h2><p className="mt-4 leading-8">Read a passage. Notice a choice. Keep something useful. Try it in your own writing, then revisit what you made. Small experiments count. If you miss a meeting, return to the current conversation; ask your teacher which exercise to pick up.</p></section><section><h2 className="literary-title text-2xl">When to share</h2><p className="mt-4 leading-8">Most exercises can stay in your notebook. The suggested review points are a scene after session 4, a draft after session 8 and a revision after session 12. Agree timing and length with your teacher before submitting.</p></section></div>
 <section className="mt-10"><h2 className="literary-title text-3xl">The journey</h2><p className="mt-3 text-studio-muted">The first two sessions are ready. Later session packs are being prepared; their outline is here to show where we are going.</p><ol className="mt-6 divide-y divide-studio-line">{courseSessions.map((s,i)=><li key={s.slug} className="grid grid-cols-[2rem_1fr] gap-4 py-6"><span className="studio-eyebrow pt-1">{String(i+1).padStart(2,'0')}</span><div><h3 className="literary-title text-2xl">{s.ready?<Link className="studio-link" href={`/app/course/${s.slug}`}>{s.title}</Link>:s.title}</h3><p className="mt-2 text-sm leading-7 text-studio-muted">{s.focus}</p>{!s.ready && <p className="mt-1 text-xs text-studio-muted">Session pack in preparation</p>}</div></li>)}</ol></section>
 <footer className="mt-8 flex flex-wrap gap-5 border-t border-studio-line pt-7"><Link className="studio-link" href="/app/course/reading-together">How we read each other’s work</Link><Link className="studio-link" href="/app/course/returning">Returning to the studio</Link><Link className="studio-link" href={teacher?'/app/teacher/documents':'/app/writer/documents'}>{teacher?'Prepare teaching materials':'Your group’s reading shelf'}</Link>{!teacher && <Link className="studio-link" href="/app/writer/commonplace">My commonplace</Link>}</footer>
 </div>}
