import Link from 'next/link'
import { courseSessions, lessons } from '@/lib/course/content'
import { IllustrationFigure } from '@/components/illustrations/illustration-figure'
import { SelectionCapture } from '@/components/commonplace/selection-capture'
import type { SaveNote } from '@/components/commonplace/note-editor'
import { PrintButton } from './print-button'
export function LessonPage({slug,teacher=false,onSave,companions=[]}:{slug:string;teacher?:boolean;onSave:SaveNote;companions?:{title:string;href:string}[]}){
 const index=courseSessions.findIndex(s=>s.slug===slug),session=courseSessions[index],lesson=lessons[slug]
 const passage=<><blockquote className="course-passage whitespace-pre-wrap font-serif text-xl leading-9">{lesson.passage}</blockquote><p className="mt-4 text-sm text-studio-muted">{lesson.source}</p></>
 return <article className="course-page mx-auto max-w-3xl"><div className="course-controls mb-7 flex flex-wrap items-center justify-between gap-4"><Link href="/app/course" className="studio-link">← Course journey</Link><PrintButton /></div>
 <header><p className="studio-eyebrow">The Short Story Workshop · Session {index+1}</p><h1 className="studio-heading mt-4">{session.title}</h1><p className="mt-5 font-serif text-xl leading-9">{lesson.invitation}</p></header>
 <div className="my-7"><IllustrationFigure attrs={{illustrationId:session.image,size:'compact'}} /></div>
 <section className="border-y border-studio-line py-6"><h2 className="studio-eyebrow">What you will try</h2><p className="mt-3 leading-8">{lesson.outcome}</p></section>
 <section className="mt-9"><h2 className="literary-title text-3xl">Read slowly</h2><div className="mt-5">{teacher?passage:<SelectionCapture source={lesson.source} sourceUrl={`/app/course/${slug}`} onSave={onSave}>{passage}</SelectionCapture>}</div></section>
 <section className="mt-9"><h2 className="literary-title text-3xl">Notice</h2><ol className="mt-4 list-decimal space-y-3 pl-6 leading-8">{lesson.questions.map(q=><li key={q}>{q}</li>)}</ol><details className="course-controls mt-5 border-l-2 border-studio-line pl-5"><summary className="cursor-pointer text-sm">One way to read this passage</summary><p className="mt-3 leading-8">{lesson.observation}</p></details><p className="hidden print:block mt-5 leading-8">{lesson.observation}</p></section>
 <section className="writing-surface mt-9 p-6 sm:p-8"><h2 className="literary-title text-3xl">Try it</h2><ol className="mt-5 list-decimal space-y-4 pl-5 leading-8">{lesson.exercise.map(step=><li key={step}>{step}</li>)}</ol><p className="mt-5 text-sm leading-7 text-studio-muted">Work in your own notebook, or in your studio draft. The studio draft is recovered on this browser; it reaches your teacher only when you submit it.</p>{!teacher && <Link className="studio-primary course-controls mt-5" href="/app/writer#writing-draft">Go to my draft</Link>}</section>
 <section className="mt-8"><h2 className="literary-title text-2xl">If you want to go further</h2><p className="mt-3 leading-8">{lesson.stretch}</p></section>
 <section className="mt-8"><h2 className="literary-title text-2xl">Return to what you wrote</h2><p className="mt-3 leading-8">{lesson.revision}</p><p className="mt-4 border-l-2 border-studio-line pl-5 font-serif text-xl leading-8">{lesson.reflection}</p></section>
 <section className="mt-8"><h2 className="literary-title text-2xl">From the teaching shelf</h2><p className="mt-3 leading-8">Companion notes: {lesson.companionTitles.join('; ')}. Your teacher may share these with your group.</p><ul className="mt-3 space-y-2">{companions.map(item=><li key={item.href}><Link className="studio-link" href={item.href}>{item.title}</Link></li>)}</ul><Link className="studio-link course-controls mt-3 inline-block" href={teacher?'/app/teacher/documents':'/app/writer/documents'}>{teacher?'Open teaching documents':'Open my group’s materials'}</Link></section>
 <footer className="mt-10 border-t border-studio-line pt-7"><p className="leading-8">{index===0?'Next, bring one detail or imagined person to “Someone particular”. There is no need to polish everything first.':'Keep this scene. In the next stage, we will explore what changes when its setting begins to exert pressure. Ask your teacher what to bring to the next meeting.'}</p><div className="course-controls mt-5 flex flex-wrap gap-5">{index===0?<Link href="/app/course/someone-particular" className="studio-primary">Next: Someone particular</Link>:<Link href="/app/course" className="studio-primary">Return to the journey</Link>}<Link href="/app/course/reading-together" className="studio-link">Reading and feedback</Link></div><p className="mt-6 text-sm text-studio-muted">shortstory.ink · Read, notice, write, revise.</p></footer>
 </article>
}
