'use client'
import { useState } from 'react'
import { craftTags, safeSourceUrl, type CommonplaceEntry, type CommonplaceInput } from '@/lib/commonplace/validation'
import { NoteEditor, type SaveNote } from './note-editor'
export function CommonplaceBook({initialEntries,onSave,onDelete,loadError=false}:{initialEntries:CommonplaceEntry[];onSave:SaveNote;onDelete:(id:string)=>Promise<{error?:string}>;loadError?:boolean}) {
 const [entries,setEntries]=useState(initialEntries),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[draft,setDraft]=useState<CommonplaceInput|null>(null),[deleting,setDeleting]=useState(''),[pending,setPending]=useState(false),[message,setMessage]=useState('')
 const visible=entries.filter(e=>(!tag||e.tag===tag)&&[e.passage,e.note,e.source].join(' ').toLowerCase().includes(query.toLowerCase().trim()))
 async function remove(id:string){setPending(true);setMessage('');try{const result=await onDelete(id);if(result.error)setMessage(result.error);else{setEntries(all=>all.filter(e=>e.id!==id));setDeleting('');setMessage('Note removed.')}}catch{setMessage('The note could not be removed. Please try again.')}finally{setPending(false)}}
 return <div className="mt-8 space-y-7">
 {loadError && <p role="alert">Your saved passages could not be loaded. Please reload before making changes.</p>}
 <div className="flex flex-wrap gap-3"><button type="button" className="studio-primary" onClick={()=>setDraft({id:crypto.randomUUID(),passage:'',source:'My observation',sourceUrl:'',note:'',tag:''})}>Keep a new note</button><label className="min-w-0 w-full sm:w-auto sm:flex-1"><span className="sr-only">Search commonplace</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search passages, sources and notes" className="course-input !mt-0" /></label><label><span className="sr-only">Filter by craft</span><select className="course-input !mt-0" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All craft</option>{craftTags.map(t=><option key={t}>{t}</option>)}</select></label></div>
 {message && <p role="status" className="text-sm">{message}</p>}
 {!loadError && visible.length===0 && <p className="border-y border-studio-line py-10 text-studio-muted">{entries.length?'No notes match this search.':'Begin with one passage or observation. Keep its source and a thought about why it matters to you.'}</p>}
 <div className="space-y-8">{visible.map(entry=><article key={entry.id} className="border-b border-studio-line pb-8"><p className="studio-eyebrow">{entry.tag || 'A saved thought'}</p><blockquote className="mt-4 whitespace-pre-wrap break-words font-serif text-xl leading-9">{entry.passage}</blockquote><p className="mt-3 break-words text-sm text-studio-muted">{entry.source}</p>{entry.note && <p className="mt-5 whitespace-pre-wrap break-words border-l-2 border-studio-line pl-4 leading-7">{entry.note}</p>}<div className="mt-5 flex flex-wrap items-center gap-4 text-sm">{safeSourceUrl(entry.sourceUrl) && <a className="studio-link" href={safeSourceUrl(entry.sourceUrl)}>Return to source</a>}<button type="button" className="studio-link" onClick={()=>setDraft(entry)}>Edit note</button><button type="button" className="studio-link" onClick={()=>setDeleting(entry.id)}>Remove note</button></div>{deleting===entry.id && <div className="mt-4 flex flex-wrap items-center gap-4"><p className="text-sm">Remove this note permanently?</p><button type="button" disabled={pending} onClick={()=>remove(entry.id)} className="studio-secondary">{pending?'Removing…':'Yes, remove'}</button><button type="button" disabled={pending} onClick={()=>setDeleting('')} className="studio-link">Keep it</button></div>}</article>)}</div>
 {draft && <NoteEditor key={draft.id} initial={draft} onSave={onSave} onClose={()=>setDraft(null)} onSaved={entry=>{setEntries(all=>[{...entry,updatedAt:new Date().toISOString()},...all.filter(e=>e.id!==entry.id)]);setDraft(null);setMessage('Saved to your private commonplace.')}} />}
 </div>
}
